Seq2SeqTrainingArguments:
  per_device_train_batch_size: 5
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  warmup_steps: 800
  max_steps: 12000
  learning_rate: 4e-5
  weight_decay: 2e-2
  fp16: True
  predict_with_generate: True
  generation_max_length: 128
  logging_steps: 50
  report_to: ["tensorboard"]
  evaluation_strategy: "steps"
  eval_steps: 400
  save_strategy: "steps"
  save_steps: 400
  load_best_model_at_end: False
  save_total_limit: 5
  metric_for_best_model: "cer"
  greater_is_better: False
  remove_unused_columns: False

LoraConfig:
  r: 32
  lora_alpha: 64
  lora_dropout: 0.1
  target_modules: ".*(encoder|decoder).*(self_attn|encoder_attn).*(q_proj|k_proj|v_proj|out_proj)$|(.*(fc1|fc2).*)"

WhisperConfig:
  apply_spec_augment: True
  mask_feature_prob: 0.1
  mask_time_prob: 0.05