batch_size: 1
beam_size: 10
penalty: 0.4
maxlenratio: 3
minlenratio: 0.0
lm_weight: 0.0
ctc_weight: 0.0
hugging_face_decoder: True

asr_beam_size: 20
asr_penalty: 0.3
asr_maxlenratio: 0.0
asr_minlenratio: 0.0
asr_lm_weight: 0.1
asr_ctc_weight: 1