Seq2SeqTrainingArguments:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 128
  gradient_accumulation_steps: 1
  warmup_steps: 2000
  max_steps: 36000
  learning_rate: 1e-3
  weight_decay: 1e-3
  fp16: True
  predict_with_generate: True
  generation_max_length: 128
  logging_steps: 50
  report_to: ["tensorboard"]
  evaluation_strategy: "steps"
  eval_steps: 1
  save_strategy: "steps"
  save_steps: 1000
  load_best_model_at_end: True
  metric_for_best_model: "wer"
  greater_is_better: False
  remove_unused_columns: False

LoraConfig:
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ".*decoder.*(self_attn|encoder_attn).*(q_proj|v_proj|out_proj)$"